### ISSUE TITLE
HCR might be blocking compilation

### ISSUE THREAD

**Issue by iusildra** [scalacenter/scala-debug-adapter#573]
While working on Dotty, I can start & restart several debug sessions, but at some point, I always end up with an infinite compile time. Also I don't know why but all the processes (metals, sbt...) have increasing memory usage with no reasons I can come up with. Might be worth double checking the stamps comparison / find a more optimized way

![image](https://github.com/scalacenter/scala-debug-adapter/assets/64749208/67f24392-f63f-4d8d-9f3b-a5d1256c3f8a)

**Comment by adpi2** [comment]
> Also I don't know why but all the processes (metals, sbt...) have increasing memory usage with no reasons I can come up with.

That does not worry me so much. Was it not increasing before HCR?

> Might be worth double checking the stamps comparison / find a more optimized way

Is it the stamp comparison that takes an infinite amount of time. Or a dead lock caused by the semaphore?

One thing we can do is to reduce the comparison of stamps to the bare minimum. We should not compare the stamps if the user did not trigger any HCR.

To do so I would remove the `observable` and the `compile` method from the `Debuggee` interface and replace them by a `classesToReload` method. 
```scala
trait Debuggee {
  def classesToReload: Seq[String]
}
```

Then in `SbtDebuggee` I would add this:
```
class SbtDebuggee (
  var previousAnalysis: Map[BuildTargetIdentifier,CompileAnalysis],
  val newAnalyisis: Map[BuildTargetIdentifier, AtomicReference[CompileAnalysis]] // The AtomicReference are set by the sbt compile task
) {

  def classesToReload: Seq[String] =
    // compare all the newAnalysis with the previous ones and update the previous ones.

}
```

**Comment by iusildra** [comment]
Fixed by handling synchronization with compilation in metals (see #570)
